### PR TITLE
ICI: Remove caching of workspace

### LINKED ISSUE #33: ICI workflow: Cache is shared between different jobs
>  > if the jobs are unique for different branches, then this would solve the case from above?
> 
> Not necessarily. Caches from PRs and scheduled builds would still get mixed up. That might be fine in most cases, but might as well lead to strange errors as the one mentioned above.
> 
> I guess, the cleanest would be:
> 
> - Use a proper job identifier (e.g. `github.workflow`)
> - Use three possbile restore keys: 
>   -  `...${{ github.base_ref }}-${{ github.ref }}`
>   - `...${{ github.base_ref }}`
>   - `...${{ github.ref }}`
> 
> This way on a PR it would search for a cache e.g. `...master-my_feature` and if it doesn't find that during the first build use `...master`, while for a scheduled build it would use `...master`, since `...master-` and `...` don't exist.
> 
> That could work, right?
> 
> Changing things to actual actions rather than reusable workflow could be a separate discussion, I think.
> 
> _Originally posted by @fmauch in https://github.com/ros-controls/ros2_control_ci/issues/30#issuecomment-1997049189_
>

### PR DESCRIPTION
**Pull request by christophfroehlich**
Fixes #33 the easiest way: just don't cache the workspace, but only ccache directory.

> Does it make sense to cache the workspace at all, how much is the speed benefit compared to only caching ccache?
> 
> * Locally, it takes 20s vs 2min if I remove the build folder.
> * [cache](https://github.com/ros-controls/ros2_control/actions/runs/8707803628/job/23883672248?pr=1485) vs [no cache](https://github.com/ros-controls/ros2_control/actions/runs/8707803627/job/23884339041?pr=1485) of ros2_control binary build: The ICI step takes the same time.

This also resolved some weird include errors while updating an upstream dependency in https://github.com/ros-controls/ros2_control/pull/1485 (yes, we could delete the caches manually but still..)

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
LGTM as all checks are green!

**Comment by fmauch** [comment]
Wait - if we remove the target_ws cache we do not increase build time? Then I really think this is worth going that route.

**Review by fmauch — APPROVED** [review]

**Comment by christophfroehlich** [comment]
> Wait - if we remove the target_ws cache we do not increase build time? Then I really think this is worth going that route.

Please verify that once again :smile: but the two workflow runs I've linked above don't show any difference.

**Comment by christophfroehlich** [comment]
Also for semi-binary builds, the build-step of ICI takes approx 30s only with/without cache (the upstream workspace was not cached anyways).

**Pull request merged**
