### PR TITLE
Add Christoph and Sai to maintainers reviewer lottery

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
Oh yeah!

**Review by christophfroehlich — COMMENTED** [review]
maybe we should remove the names from the lower revier section?

**Review by christophfroehlich — APPROVED** [review]
I removed us two from the reviewers list, I don't know how that works if a user being in the same list.
And I increased internal_reviewers, as we require two approvals of "users with write access", and the PR author does not count.

**Comment by bmagyar** [comment]
I'm too used to using the override ;)

**Pull request merged**
